# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aap0037_hehJayAccRejCheckBx.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_DynoChartTaskPanel_exp(object):
    def setupUi(self, DynoChartTaskPanel_exp):
        DynoChartTaskPanel_exp.setObjectName("DynoChartTaskPanel_exp")
        DynoChartTaskPanel_exp.resize(405, 391)
        self.DynoChartTaskPanel_Bx = QtWidgets.QDialogButtonBox(DynoChartTaskPanel_exp)
        self.DynoChartTaskPanel_Bx.setGeometry(QtCore.QRect(20, 310, 171, 32))
        self.DynoChartTaskPanel_Bx.setOrientation(QtCore.Qt.Horizontal)
        self.DynoChartTaskPanel_Bx.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.DynoChartTaskPanel_Bx.setObjectName("DynoChartTaskPanel_Bx")
        self.grpbx_master = QtWidgets.QGroupBox(DynoChartTaskPanel_exp)
        self.grpbx_master.setGeometry(QtCore.QRect(8, 20, 231, 289))
        self.grpbx_master.setTitle("")
        self.grpbx_master.setObjectName("grpbx_master")
        self.grpbx_sprdsheet = QtWidgets.QGroupBox(self.grpbx_master)
        self.grpbx_sprdsheet.setGeometry(QtCore.QRect(0, 0, 221, 201))
        self.grpbx_sprdsheet.setObjectName("grpbx_sprdsheet")
        self.chkbx_FntMotorDyno = QtWidgets.QCheckBox(self.grpbx_sprdsheet)
        self.chkbx_FntMotorDyno.setGeometry(QtCore.QRect(0, 30, 181, 23))
        self.chkbx_FntMotorDyno.setObjectName("chkbx_FntMotorDyno")
        self.chkbx_RrMotorDyno = QtWidgets.QCheckBox(self.grpbx_sprdsheet)
        self.chkbx_RrMotorDyno.setGeometry(QtCore.QRect(0, 50, 191, 23))
        self.chkbx_RrMotorDyno.setObjectName("chkbx_RrMotorDyno")
        self.chkbx_AxleTorque = QtWidgets.QCheckBox(self.grpbx_sprdsheet)
        self.chkbx_AxleTorque.setGeometry(QtCore.QRect(0, 70, 151, 23))
        self.chkbx_AxleTorque.setObjectName("chkbx_AxleTorque")
        self.chkbx_VehForces = QtWidgets.QCheckBox(self.grpbx_sprdsheet)
        self.chkbx_VehForces.setGeometry(QtCore.QRect(0, 90, 181, 23))
        self.chkbx_VehForces.setObjectName("chkbx_VehForces")
        self.chkbx_WheelPwr = QtWidgets.QCheckBox(self.grpbx_sprdsheet)
        self.chkbx_WheelPwr.setGeometry(QtCore.QRect(0, 110, 211, 23))
        self.chkbx_WheelPwr.setObjectName("chkbx_WheelPwr")
        self.chkbx_AccelTraction = QtWidgets.QCheckBox(self.grpbx_sprdsheet)
        self.chkbx_AccelTraction.setGeometry(QtCore.QRect(0, 130, 201, 23))
        self.chkbx_AccelTraction.setObjectName("chkbx_AccelTraction")
        self.chkbx_FnBatteryCapa = QtWidgets.QCheckBox(self.grpbx_sprdsheet)
        self.chkbx_FnBatteryCapa.setGeometry(QtCore.QRect(0, 150, 191, 23))
        self.chkbx_FnBatteryCapa.setObjectName("chkbx_FnBatteryCapa")
        self.chkbx_RrBatteryCapa = QtWidgets.QCheckBox(self.grpbx_sprdsheet)
        self.chkbx_RrBatteryCapa.setGeometry(QtCore.QRect(0, 170, 181, 23))
        self.chkbx_RrBatteryCapa.setObjectName("chkbx_RrBatteryCapa")
        self.groupBox_3 = QtWidgets.QGroupBox(self.grpbx_master)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 200, 221, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(0, 30, 131, 17))
        self.label.setObjectName("label")
        self.spinbx_Rows = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinbx_Rows.setGeometry(QtCore.QRect(160, 30, 44, 26))
        self.spinbx_Rows.setMinimum(2)
        self.spinbx_Rows.setMaximum(52)
        self.spinbx_Rows.setProperty("value", 16)
        self.spinbx_Rows.setObjectName("spinbx_Rows")

        self.retranslateUi(DynoChartTaskPanel_exp)
        self.DynoChartTaskPanel_Bx.accepted.connect(DynoChartTaskPanel_exp.update) # type: ignore
        self.DynoChartTaskPanel_Bx.rejected.connect(DynoChartTaskPanel_exp.update) # type: ignore
        self.DynoChartTaskPanel_Bx.rejected.connect(DynoChartTaskPanel_exp.spinValueChanged) # type: ignore
        self.spinbx_Rows.valueChanged['int'].connect(self.label.setNum) # type: ignore
        self.DynoChartTaskPanel_Bx.accepted.connect(DynoChartTaskPanel_exp.on_sliderFuel_valueChanged) # type: ignore
        self.spinbx_Rows.valueChanged['int'].connect(DynoChartTaskPanel_exp.spinValueChanged) # type: ignore
        self.DynoChartTaskPanel_Bx.clicked['QAbstractButton*'].connect(DynoChartTaskPanel_exp.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DynoChartTaskPanel_exp)

    def retranslateUi(self, DynoChartTaskPanel_exp):
        _translate = QtCore.QCoreApplication.translate
        DynoChartTaskPanel_exp.setWindowTitle(_translate("DynoChartTaskPanel_exp", "Dialog"))
        self.grpbx_sprdsheet.setTitle(_translate("DynoChartTaskPanel_exp", "Select Plots to View"))
        self.chkbx_FntMotorDyno.setText(_translate("DynoChartTaskPanel_exp", "Front Motor Dyno Chart"))
        self.chkbx_RrMotorDyno.setText(_translate("DynoChartTaskPanel_exp", "Rear Motor Dyno Chart"))
        self.chkbx_AxleTorque.setText(_translate("DynoChartTaskPanel_exp", "Axle Torque"))
        self.chkbx_VehForces.setText(_translate("DynoChartTaskPanel_exp", "Vehicle Forces at Play"))
        self.chkbx_WheelPwr.setText(_translate("DynoChartTaskPanel_exp", "Wheel Power - Battery Limit"))
        self.chkbx_AccelTraction.setText(_translate("DynoChartTaskPanel_exp", "Acceleration - Traction Est."))
        self.chkbx_FnBatteryCapa.setText(_translate("DynoChartTaskPanel_exp", "Front Battery Capability"))
        self.chkbx_RrBatteryCapa.setText(_translate("DynoChartTaskPanel_exp", "Rear Battery Capability"))
        self.groupBox_3.setTitle(_translate("DynoChartTaskPanel_exp", "Manage Data Rows"))
        self.label.setText(_translate("DynoChartTaskPanel_exp", "Adjust Rows to Plot"))
        self.spinbx_Rows.setToolTip(_translate("DynoChartTaskPanel_exp", "Default: 16. Range: 2-50"))


if __name__ == "__main__":
    import sys
    #app = QtWidgets.QApplication(sys.argv)
    DynoChartTaskPanel_exp = QtWidgets.QDialog()
    ui = Ui_DynoChartTaskPanel_exp()
    ui.setupUi(DynoChartTaskPanel_exp)
    DynoChartTaskPanel_exp.show()
    #ys.exit(app.exec_())
